### ISSUE TITLE
Grid is not able to handle the amount of cells that we need

### ISSUE THREAD

**Issue by ByronAmbright** [ByronAmbright/Rudolph#6]

**Comment by bookdude13** [comment]
One way to deal with this is only rendering the cells that are currently on the screen. Would add complexity to our code, but might be worth it

**Comment by ByronAmbright** [comment]
I was looking at node modules online to see if any would already do the screen render for us and could not find anything that really would work. For the moment our grid is really stuggling to do a 3 channel 6min song. I was trying to do things with the scrolling and using those to detect what the screen is but got little progress done.  The only problem with the render being rows at a time is that it might be hard to not render the rest of the row depending on the screen.  I will probably not be around the next few days so let me know if you get to this.

**Comment by theeldestelder** [comment]
Only rendering the cells currently on the screen looks like the way to go.  The React documentation [recommends](https://reactjs.org/docs/optimizing-performance.html#virtualize-long-lists) doing that.  It also points to a windowing library called [React Virtualized](https://bvaughn.github.io/react-virtualized/#/components/Grid) and that seems to work decently.  

We probably don't need the whole library, but using some of the ideas behind it to build our own windower would help ours become more usable.

**Comment by bookdude13** [comment]
I don't see a problem with just using that library. It looks like exactly what we want.
https://github.com/bvaughn/react-virtualized/blob/master/docs/Grid.md#basic-grid-example

**Comment by theeldestelder** [comment]
It definitely would save us a lot of trouble.

**Comment by ByronAmbright** [comment]
yeah I have been working for awhile now trying to get this to render nicely, and haven't had much luck. I can try implementing it using react virtualized.

**Comment by ByronAmbright** [comment]
Updated Sequencer with Suggestions. I think that we should focus on making it functional after this PR before we move on to other Ideas to ensure this is what is going to be the base of the program. I think Ryan's Idea of having a background grid is a good idea, as it will trick the user into seeing a correctly loaded grid. The only thing the background has to do is to match the actual grid because we will be having the color of the cell changing not adding an x, so it will be noticeable if the user is scrolling and sees the white background switch to a colored cell, if that makes sense. I can work on making the cells change to the color of the row when it is clicked, and adding the background. Someone should also work on formating a json file as output so we can save the data and in a format that can be read by the cli interface, this might be best for Ryan as he knows how the data is being read. This will help us see if the grid that stores values is slowing the render process down as it has to continually find the current value in the array every time it is rendered. Also, probably Josh if you want to, we should now implement it being able to "play" where it scrolls across the screen with a line. This will help us judge how bad the rendering lag  is when it is scrolling left to right.

**Comment by theeldestelder** [comment]
> The only thing the background has to do is to match the actual grid

In Vixen, you could change the zoom levels of the grid (10 - 100%) for both rows and columns which changed the size of the cells.  If we want to do that, the background image has to be dependent whatever the current cell size is.  Don't know what the correct implementation is, but figured I'd throw this thought out there.

> we should now implement it being able to "play" where it scrolls across the screen with a line

I'll start working on it.

**Comment by bookdude13** [comment]
> work on formating a json file as output so we can save the data and in a format that can be read by the cli interface

I can start working on that now.

> see if the grid that stores values is slowing the render process down as it has to continually find the current value in the array every time it is rendered

How else would we do this? It needs the value to properly render...

**Comment by bookdude13** [comment]
And the background image idea may not fly. The colors will keep changing (like you pointed out), so hard to have something to trick the user.
